apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostflow-deployment
  namespace: default
  labels:
    app: boostflow
spec:
  selector:
    matchLabels:
      app: boostflow
  replicas: 2
  template:
    metadata:
      labels:
        app: boostflow
    spec:
      containers:
      - name: boostflow
        image: ghcr.io/nikosd767/boostflow:latest
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        # App Configuration from ConfigMap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: node-env
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app-url
        - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: google-maps-api-key
        - name: GEMINI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gemini-api-key
        
        # Firebase Configuration from Secret
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: api-key
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: auth-domain
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: project-id
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: storage-bucket
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: messaging-sender-id
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: app-id
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: measurement-id
        - name: FIREBASE_SERVICE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: service-account-key
        
        # MinIO Configuration from Secret
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: endpoint
        - name: MINIO_EXTERNAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: external-endpoint
        - name: MINIO_PORT
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: port
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: root-password
        - name: MINIO_USE_SSL
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: use-ssl
        - name: MINIO_PROFILE_PICTURES_BUCKET
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: profile-pictures-bucket
        - name: MINIO_PROJECT_DOCUMENTS_BUCKET
          valueFrom:
            secretKeyRef:
              name: minio-config
              key: project-documents-bucket
        
        # OAuth Configuration from Secret
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: google-client-id
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: google-client-secret
        - name: NEXT_PUBLIC_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: github-client-id
        - name: NEXT_PUBLIC_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: github-client-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: google-client-secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: github-client-secret
        - name: NEXT_PUBLIC_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: oauth-client-id
        
        # Email Configuration from Secret
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: email-config
              key: sendgrid-api-key
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-config
              key: default-from-email
        - name: MAILHOG_HOST
          valueFrom:
            secretKeyRef:
              name: email-config
              key: mailhog-host
        - name: MAILHOG_PORT
          valueFrom:
            secretKeyRef:
              name: email-config
              key: mailhog-port
        ports:
        - containerPort: 3000
          name: boostflow
      imagePullSecrets:
      - name: registry-credentials