apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostflow-deployment
  namespace: default
  labels:
    app: boostflow
spec:
  selector:
    matchLabels:
      app: boostflow
  replicas: 2
  template:
    metadata:
      labels:
        app: boostflow
    spec:
      containers:
      - name: boostflow
        image: ghcr.io/nikosd767/boostflow:latest
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: api-key
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: auth-domain
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: project-id
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: storage-bucket
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: messaging-sender-id
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: app-id
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: measurement-id
        ports:
        - containerPort: 3000
          name: boostflow
      imagePullSecrets:
      - name: registry-credentials